%% getPitch
% parameters: 1-channel audio
% output: pitch in hz

function p = getPitch(audio,fs)
    p = pitch(audio, fs, ...
        "WindowLength",size(audio,1), ...
        "OverlapLength",0, ...
        "Range",[100,2000], ...
        "Method","PEF");
end

